project:
  type: website

website:
  description: "Talousblogi"
  site-url: https://vkauppine.github.io/talousblogi/
  title: "Incentive Lens"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    lang: fi



